#!/bin/bash
set -euC
cd "$(dirname "$0")/../"

usage() {
  "$(dirname "$0")/help" exec
}

cmdname="$1"
appname="$1"
shift

if [ ! -d "apps/$appname" ]; then
  echo "Package $appname is not installed." >&2
  echo "Try: pungi install $appname" >&2
  exit -1
fi

cmd="apps/$appname/bin/$cmdname"
if [ ! -f "$cmd" ]; then
  echo "Command $cmdname is not given by package $appname." >&2
  exit -1
fi

exec "$cmd" "$@"
