#!/bin/bash
set -euC
cd "$(dirname "$0")/../"

usage() {
  "$(dirname "$0")/help" install
}

pyenv_required() {
  echo 'pyenv command is required.'
  echo 'For pyenv information, see: https://github.com/pyenv/pyenv'
}

latest_python_version() {
  pyenv install -l | tr -d ' ' | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' | sort -n | tail -1
}

version_spec=''
name=''
python_version=''

while [ $# -gt 0 ]; do
  case "$1" in
    '-h' | '--help')
      usage && exit
    ;;
    '-v' )
      shift
      version_spec="==$1"
    ;;
    '--name' )
      shift
      name="$1"
      shift
    ;;
    '--python' )
      shift
      python_version="$1"
      shift
    ;;
    * )
      break
    ;;
  esac
done

if [ $# -ne 1 ]; then
  usage >&2
  exit -1
fi
pkg="$1"

if ! command -v pyenv > /dev/null; then
  pyenv_required >&2
  exit -1
fi

if [ -z "$python_version" ]; then
  python_version="$(latest_python_version)"
fi

if ! ( pyenv versions --bare | grep "$python_version" > /dev/null ); then
  pyenv install "$python_version"
fi

if [ -z "${PYENV_ROOT}" ]; then
  pyenv_root="${HOME}/.pyenv"
else
  pyenv_root="${PYENV_ROOT%/}"
fi

"$pyenv_root/versions/$python_version/bin/venv" "apps/$name/"
"apps/$name/bin/pip" install "$pkg$version_spec"
echo "$pkg" > "apps/$name/info/pkg"
